require('pkgs.bufferline')
require('pkgs.github-themes')
require('pkgs.lualine')
require('pkgs.material')
require('pkgs.nvim-tree')
require('pkgs.comment')
require('pkgs.telescope')
require('pkgs.cmp')
require('pkgs.nvim-autopairs')
require('pkgs.treesitter')

