require('pkgs.nvim-notify')
require('pkgs.bufferline')
-- require('pkgs.github-themes')
require('pkgs.lualine')
require('pkgs.gitsigns')
require('pkgs.material')
require('pkgs.nvim-tree')
require('pkgs.nvim-web-devicons')
require('pkgs.comment')
require('pkgs.telescope')
require('pkgs.cmp')
require('pkgs.nvim-autopairs')
require('pkgs.treesitter')
require('pkgs.luasnip')
require('pkgs.floaterm')
require('pkgs.catppuccin')
require('pkgs.nvim-surround')
require('pkgs.tailwind-sorter')
-- require('pkgs.silicon')
require('pkgs.ufo')
-- require('pkgs.oxocarbon')

